### ISSUE TITLE
유료앱 출시전 개선 사항

### ISSUE THREAD

**Issue by claudebaek** [claudebaek/VoiceAlarm#3]
아무말 안할경우 이전 데이터 입력되는 문제.
내일 아침/저녁 몇시 -> 아침/저녁은 입력에서 제외
오전만 말할경우 -> 오전 9시 세팅
오후만 말할경우 -> 오후 1시 세팅
모레 + 모래.몰애,몰에

------------

초기설치시 메뉴얼보여주기

**Comment by myunggu** [comment]
이슈 수정 완료.
