### ISSUE TITLE
2차 업데이트 예정사항

### ISSUE THREAD

**Issue by claudebaek** [claudebaek/VoiceAlarm#4]
<버그>

- 1시간 후(뒤) -> '후(뒤)' 는 입력 안되도록

- 특정 날짜 + 시간 제외한 오전(오후) -> 입력불가 

- 저녁 12~1시 사이 알림안옴.

- 인앱 미구매시 복원하기 크래쉬

<개선사항>

- 반복 알림 기능 추가 
- 사운드 추가
- 최초 실행시 튜토리얼

**Comment by myunggu** [comment]
수정 완료 항목 : 
. 1시간 후(뒤) -> '후(뒤)' 는 입력 안되도록 
. 특정 날짜 + 시간 제외한 오전(오후) -> 입력불가

release 에 업데이트 함.
